#!/usr/bin/env python

import sys
from optparse import OptionParser

from json_grep import JSONGrep

# -----------------------------------
# Main
# -----------------------------------
def parse_args():
   parser = OptionParser()
   parser.add_option('-k', '--key' , dest='keys', action='append',
                     help='List of JSON keys to output, arg for each key')

   options, args = parser.parse_args()
   if len(args) != 1:
       parser.error('Must specify a file.')
       sys.exit()

   if not options.keys:
       parser.error('Must specify at least one key regex')
       sys.exit()

   return options, args

if __name__ == '__main__':
   options, args = parse_args()
   json_grep = JSONGrep(options.keys)
   
   for line in json_grep.jgrep_file(args[0]):
       print '%s' % line
